### ISSUE TITLE
doc: fix usage description about response body

### ISSUE THREAD

**Issue by tesibelda** [TwiN/health#1]
### Describe the bug

Thanks for your code. Readme.md file contains this: 'By default, the handler will return UP when the status is down, '.

### What do you expect to see?

I guess it should be changed to: ''By default, the handler will return UP when the status is up, ', just to avoid misunderstanding the new users.

### List the steps that must be taken to reproduce this issue

Just read Usage at Readme.md file

**Comment by TwiN** [comment]
@tesibelda Good catch 😅 

Would you like to create a PR for it? No worries if you'd rather not :)

**Comment by tesibelda** [comment]
Sure: #2
